(function() {var implementors = {};
implementors["cgmath"] = [{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"cgmath/trait.BaseFloat.html\" title=\"trait cgmath::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"cgmath/prelude/trait.One.html\" title=\"trait cgmath::prelude::One\">One</a> for <a class=\"struct\" href=\"cgmath/struct.Matrix2.html\" title=\"struct cgmath::Matrix2\">Matrix2</a>&lt;S&gt;",synthetic:false,types:["cgmath::matrix::Matrix2"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"cgmath/trait.BaseFloat.html\" title=\"trait cgmath::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"cgmath/prelude/trait.One.html\" title=\"trait cgmath::prelude::One\">One</a> for <a class=\"struct\" href=\"cgmath/struct.Matrix3.html\" title=\"struct cgmath::Matrix3\">Matrix3</a>&lt;S&gt;",synthetic:false,types:["cgmath::matrix::Matrix3"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"cgmath/trait.BaseFloat.html\" title=\"trait cgmath::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"cgmath/prelude/trait.One.html\" title=\"trait cgmath::prelude::One\">One</a> for <a class=\"struct\" href=\"cgmath/struct.Matrix4.html\" title=\"struct cgmath::Matrix4\">Matrix4</a>&lt;S&gt;",synthetic:false,types:["cgmath::matrix::Matrix4"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"cgmath/trait.BaseFloat.html\" title=\"trait cgmath::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"cgmath/prelude/trait.One.html\" title=\"trait cgmath::prelude::One\">One</a> for <a class=\"struct\" href=\"cgmath/struct.Quaternion.html\" title=\"struct cgmath::Quaternion\">Quaternion</a>&lt;S&gt;",synthetic:false,types:["cgmath::quaternion::Quaternion"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"cgmath/trait.BaseFloat.html\" title=\"trait cgmath::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"cgmath/prelude/trait.One.html\" title=\"trait cgmath::prelude::One\">One</a> for <a class=\"struct\" href=\"cgmath/struct.Basis2.html\" title=\"struct cgmath::Basis2\">Basis2</a>&lt;S&gt;",synthetic:false,types:["cgmath::rotation::Basis2"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"cgmath/trait.BaseFloat.html\" title=\"trait cgmath::BaseFloat\">BaseFloat</a>&gt; <a class=\"trait\" href=\"cgmath/prelude/trait.One.html\" title=\"trait cgmath::prelude::One\">One</a> for <a class=\"struct\" href=\"cgmath/struct.Basis3.html\" title=\"struct cgmath::Basis3\">Basis3</a>&lt;S&gt;",synthetic:false,types:["cgmath::rotation::Basis3"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
